######################################################################
# Automatically generated by qmake (3.1) Sun Jul 5 21:30:01 2026
######################################################################

TEMPLATE = subdirs

# Directories
QT += widgets network gui
