name: Windows Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'

    - name: Build with CMake
      run: |
        cmake -B build_win
        cmake --build build_win --config Release

    - name: Deploy Qt Dependencies
      run: |
        cd build_win/Release
        windeployqt --release --compiler-runtime KmlArcGenerator.exe
        $qtBin = Split-Path (Get-Command windeployqt).Source -Parent
        Copy-Item "$qtBin\Qt6*.dll" -Destination . -ErrorAction SilentlyContinue

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: KmlArcGenerator-Windows-Exe
        path: build_win/Release/
