name: Windows Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build with CMake
      run: |
        cmake -B build_win -G "Visual Studio 17 2022" -A x64
        cmake --build build_win --config Release

    - name: Deploy Qt Dependencies
      run: |
        cd build_win/Release
        windeployqt KmlArcGenerator.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: KmlArcGenerator-Windows-Exe
        path: build_win/Release/
